import sys
import os

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except:
        pass

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.app.database import SessionLocal, Base, engine
from backend.app.models.food import Food

# 100 Indian Foods Dataset migrated from existing NutriVision
INDIAN_FOODS_DATASET = [
  {"name": "Chapati / Whole Wheat Roti", "regional_name": "Phulka / Roti", "category": "Bread", "serving_size": "1 piece (35g)", "serving_weight_g": 35, "emoji": "🫓", "calories": 104, "protein": 3.4, "carbohydrates": 20.0, "fat": 0.5, "fiber": 2.5, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 5.0, "vegetarian": True, "vegan": True},
  {"name": "Basmati Rice (cooked)", "regional_name": "Sada Chawal", "category": "Rice", "serving_size": "1 cup (150g)", "serving_weight_g": 150, "emoji": "🍚", "calories": 130, "protein": 2.7, "carbohydrates": 28.0, "fat": 0.3, "fiber": 0.4, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 10.0, "vegetarian": True, "vegan": True},
  {"name": "Paratha (plain)", "regional_name": "Sada Paratha", "category": "Bread", "serving_size": "1 piece (60g)", "serving_weight_g": 60, "emoji": "🥞", "calories": 168, "protein": 4.0, "carbohydrates": 25.0, "fat": 6.0, "fiber": 2.1, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 15.0, "vegetarian": True, "vegan": False},
  {"name": "Paratha (stuffed aloo)", "regional_name": "Aloo Paratha", "category": "Bread", "serving_size": "1 piece (100g)", "serving_weight_g": 100, "emoji": "🥞", "calories": 210, "protein": 4.5, "carbohydrates": 32.0, "fat": 8.0, "fiber": 3.0, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": False},
  {"name": "Naan", "regional_name": "Tandoori Naan", "category": "Bread", "serving_size": "1 piece (90g)", "serving_weight_g": 90, "emoji": "🫓", "calories": 262, "protein": 9.0, "carbohydrates": 45.0, "fat": 5.0, "fiber": 1.9, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 25.0, "vegetarian": True, "vegan": False},
  {"name": "Puri", "regional_name": "Crispy Deep-Fried Puri", "category": "Bread", "serving_size": "1 piece (30g)", "serving_weight_g": 30, "emoji": "🫓", "calories": 152, "protein": 3.0, "carbohydrates": 18.0, "fat": 8.0, "fiber": 1.2, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 8.0, "vegetarian": True, "vegan": True},
  {"name": "Idli", "regional_name": "Steamed Rice & Urad Cake", "category": "South Indian", "serving_size": "1 piece (40g)", "serving_weight_g": 40, "emoji": "🍱", "calories": 39, "protein": 2.0, "carbohydrates": 7.5, "fat": 0.1, "fiber": 0.5, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 8.0, "vegetarian": True, "vegan": True},
  {"name": "Dosa (plain)", "regional_name": "Sada Dosa", "category": "South Indian", "serving_size": "1 piece (80g)", "serving_weight_g": 80, "emoji": "🥞", "calories": 133, "protein": 3.5, "carbohydrates": 22.0, "fat": 3.5, "fiber": 0.8, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 35.0, "vegetarian": True, "vegan": True},
  {"name": "Poha", "regional_name": "Kanda Poha", "category": "Breakfast", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🍱", "calories": 180, "protein": 3.0, "carbohydrates": 32.0, "fat": 5.0, "fiber": 2.0, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Upma", "regional_name": "Rava Upma", "category": "Breakfast", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🍱", "calories": 160, "protein": 4.0, "carbohydrates": 25.0, "fat": 5.0, "fiber": 2.5, "protein_quality_score": 0.45, "bioavailability_label": "Low", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  
  # Dals & Pulses
  {"name": "Dal Tadka", "regional_name": "Peeli Dal Tadka", "category": "Dal", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍛", "calories": 180, "protein": 9.0, "carbohydrates": 25.0, "fat": 6.0, "fiber": 5.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 35.0, "vegetarian": True, "vegan": True},
  {"name": "Dal Makhani", "regional_name": "Urad & Cream Dal", "category": "Dal", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍛", "calories": 280, "protein": 11.0, "carbohydrates": 28.0, "fat": 14.0, "fiber": 6.0, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 60.0, "vegetarian": True, "vegan": False},
  {"name": "Rajma Curry", "regional_name": "Kashmiri Rajma", "category": "Dal", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍛", "calories": 250, "protein": 13.0, "carbohydrates": 32.0, "fat": 8.0, "fiber": 8.0, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 45.0, "vegetarian": True, "vegan": True},
  {"name": "Chana Masala", "regional_name": "Chole / Chana", "category": "Dal", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍛", "calories": 240, "protein": 12.0, "carbohydrates": 35.0, "fat": 7.0, "fiber": 7.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 40.0, "vegetarian": True, "vegan": True},
  {"name": "Moong Dal (cooked)", "regional_name": "Dhuli Moong", "category": "Dal", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍛", "calories": 110, "protein": 7.0, "carbohydrates": 19.0, "fat": 0.5, "fiber": 4.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Sambar", "regional_name": "South Indian Sambar", "category": "South Indian", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍲", "calories": 130, "protein": 6.0, "carbohydrates": 18.0, "fat": 4.0, "fiber": 4.0, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Kadhi Pakoda", "regional_name": "Besan Kadhi with Pakoda", "category": "Curry", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍲", "calories": 220, "protein": 7.0, "carbohydrates": 22.0, "fat": 12.0, "fiber": 2.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 35.0, "vegetarian": True, "vegan": False},
  {"name": "Chole", "regional_name": "Amritsari Chole", "category": "Dal", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍛", "calories": 230, "protein": 11.0, "carbohydrates": 36.0, "fat": 6.0, "fiber": 7.0, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 40.0, "vegetarian": True, "vegan": True},

  # Vegetables & Sabzi
  {"name": "Paneer Butter Masala", "regional_name": "Makhani Paneer", "category": "Curry", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🧀", "calories": 380, "protein": 18.0, "carbohydrates": 18.0, "fat": 28.0, "fiber": 2.0, "calcium_mg": 380, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 80.0, "vegetarian": True, "vegan": False},
  {"name": "Palak Paneer", "regional_name": "Spinach Cottage Cheese", "category": "Curry", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🥬", "calories": 280, "protein": 16.0, "carbohydrates": 12.0, "fat": 18.0, "fiber": 3.8, "calcium_mg": 410, "iron_mg": 3.5, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 70.0, "vegetarian": True, "vegan": False},
  {"name": "Shahi Paneer", "regional_name": "Royal Cashew Paneer", "category": "Curry", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🧀", "calories": 350, "protein": 15.0, "carbohydrates": 20.0, "fat": 24.0, "fiber": 2.0, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 85.0, "vegetarian": True, "vegan": False},
  {"name": "Paneer (raw, 100g)", "regional_name": "Fresh Cottage Cheese", "category": "Dairy", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🧀", "calories": 265, "protein": 18.0, "carbohydrates": 1.2, "fat": 20.0, "fiber": 0.0, "calcium_mg": 480, "b12_mcg": 0.4, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 45.0, "vegetarian": True, "vegan": False},
  {"name": "Aloo Gobi", "regional_name": "Potato & Cauliflower", "category": "Curry", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🥦", "calories": 120, "protein": 3.0, "carbohydrates": 18.0, "fat": 4.0, "fiber": 3.5, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Bhindi Masala", "regional_name": "Spiced Okra", "category": "Curry", "serving_size": "1 bowl (160g)", "serving_weight_g": 160, "emoji": "🫑", "calories": 110, "protein": 2.0, "carbohydrates": 15.0, "fat": 4.0, "fiber": 4.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 35.0, "vegetarian": True, "vegan": True},
  {"name": "Baingan Bharta", "regional_name": "Mashed Eggplant", "category": "Curry", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🍆", "calories": 135, "protein": 3.0, "carbohydrates": 16.0, "fat": 7.0, "fiber": 5.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 35.0, "vegetarian": True, "vegan": True},
  {"name": "Matar Paneer", "regional_name": "Peas Paneer Curry", "category": "Curry", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🧀", "calories": 290, "protein": 14.0, "carbohydrates": 22.0, "fat": 18.0, "fiber": 4.0, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 60.0, "vegetarian": True, "vegan": False},
  {"name": "Mixed Veg Curry", "regional_name": "Mix Sabzi", "category": "Curry", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🥘", "calories": 140, "protein": 4.0, "carbohydrates": 20.0, "fat": 5.0, "fiber": 4.5, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 35.0, "vegetarian": True, "vegan": True},
  {"name": "Raita", "regional_name": "Spiced Curd Raita", "category": "Dairy", "serving_size": "1 bowl (150g)", "serving_weight_g": 150, "emoji": "🥛", "calories": 80, "protein": 4.0, "carbohydrates": 8.0, "fat": 3.0, "fiber": 1.0, "calcium_mg": 140, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 20.0, "vegetarian": True, "vegan": False},

  # Non-Veg & Eggs
  {"name": "Chicken Biryani", "regional_name": "Dum Chicken Biryani", "category": "Non-Veg", "serving_size": "1 plate (350g)", "serving_weight_g": 350, "emoji": "🍗", "calories": 490, "protein": 28.0, "carbohydrates": 55.0, "fat": 15.0, "fiber": 2.5, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 150.0, "vegetarian": False},
  {"name": "Chicken Tikka Masala", "regional_name": "Tandoori Tikka Gravy", "category": "Non-Veg", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🍗", "calories": 310, "protein": 30.0, "carbohydrates": 12.0, "fat": 16.0, "fiber": 1.5, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 120.0, "vegetarian": False},
  {"name": "Chicken Curry", "regional_name": "Desi Chicken Curry", "category": "Non-Veg", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🍗", "calories": 280, "protein": 28.0, "carbohydrates": 8.0, "fat": 16.0, "fiber": 1.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 100.0, "vegetarian": False},
  {"name": "Tandoori Chicken (200g)", "regional_name": "Charcoal Tandoori Chicken", "category": "Non-Veg", "serving_size": "200g", "serving_weight_g": 200, "emoji": "🍗", "calories": 220, "protein": 35.0, "carbohydrates": 5.0, "fat": 7.0, "fiber": 1.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 120.0, "vegetarian": False},
  {"name": "Chicken Tikka (100g)", "regional_name": "Boneless Chicken Tikka", "category": "Non-Veg", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🍗", "calories": 165, "protein": 28.0, "carbohydrates": 4.0, "fat": 5.0, "fiber": 0.5, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 90.0, "vegetarian": False},
  {"name": "Mutton Curry", "regional_name": "Rogan Josh / Gosht Curry", "category": "Non-Veg", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🥩", "calories": 340, "protein": 25.0, "carbohydrates": 8.0, "fat": 23.0, "fiber": 0.5, "iron_mg": 2.8, "b12_mcg": 2.5, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 180.0, "vegetarian": False},
  {"name": "Egg Bhurji (2 eggs)", "regional_name": "Indian Scrambled Eggs", "category": "Egg", "serving_size": "1 plate (120g)", "serving_weight_g": 120, "emoji": "🥚", "calories": 200, "protein": 14.0, "carbohydrates": 4.0, "fat": 14.0, "fiber": 0.5, "b12_mcg": 1.2, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 35.0, "vegetarian": False, "contains_egg": True},
  {"name": "Boiled Egg", "regional_name": "Ubla Anda", "category": "Egg", "serving_size": "1 piece (50g)", "serving_weight_g": 50, "emoji": "🥚", "calories": 78, "protein": 6.0, "carbohydrates": 0.6, "fat": 5.3, "fiber": 0.0, "b12_mcg": 0.6, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 8.0, "vegetarian": False, "contains_egg": True},
  {"name": "Omelette (2 eggs)", "regional_name": "Masala Omelette", "category": "Egg", "serving_size": "1 plate (120g)", "serving_weight_g": 120, "emoji": "🍳", "calories": 190, "protein": 13.0, "carbohydrates": 2.0, "fat": 14.0, "fiber": 0.5, "b12_mcg": 1.2, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 35.0, "vegetarian": False, "contains_egg": True},
  {"name": "Fish Curry", "regional_name": "Macher Jhol", "category": "Non-Veg", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🐟", "calories": 240, "protein": 24.0, "carbohydrates": 8.0, "fat": 12.0, "fiber": 0.5, "omega_3_g": 1.2, "b12_mcg": 2.1, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 95.0, "vegetarian": False},
  {"name": "Prawn Masala", "regional_name": "Jhinga Masala", "category": "Non-Veg", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🦐", "calories": 210, "protein": 22.0, "carbohydrates": 6.0, "fat": 11.0, "fiber": 0.5, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 140.0, "vegetarian": False},
  {"name": "Mutton Biryani", "regional_name": "Gosht Dum Biryani", "category": "Non-Veg", "serving_size": "1 plate (350g)", "serving_weight_g": 350, "emoji": "🥩", "calories": 560, "protein": 30.0, "carbohydrates": 60.0, "fat": 20.0, "fiber": 2.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 220.0, "vegetarian": False},

  # Snacks & Street Food
  {"name": "Samosa (1 piece)", "regional_name": "Aloo Samosa", "category": "Snack", "serving_size": "1 piece (80g)", "serving_weight_g": 80, "emoji": "🥟", "calories": 262, "protein": 4.0, "carbohydrates": 32.0, "fat": 14.0, "fiber": 2.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 15.0, "vegetarian": True, "vegan": True},
  {"name": "Pakora (100g)", "regional_name": "Besan Onion Pakoda", "category": "Snack", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🧆", "calories": 280, "protein": 6.0, "carbohydrates": 28.0, "fat": 16.0, "fiber": 3.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Vada Pav", "regional_name": "Mumbai Vada Pav", "category": "Snack", "serving_size": "1 piece (120g)", "serving_weight_g": 120, "emoji": "🍔", "calories": 290, "protein": 7.0, "carbohydrates": 42.0, "fat": 11.0, "fiber": 2.5, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Pav Bhaji", "regional_name": "Butter Pav Bhaji", "category": "Snack", "serving_size": "1 plate (250g)", "serving_weight_g": 250, "emoji": "🍞", "calories": 380, "protein": 9.0, "carbohydrates": 52.0, "fat": 14.0, "fiber": 5.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 60.0, "vegetarian": True, "vegan": False},
  {"name": "Bhel Puri", "regional_name": "Mumbai Bhel Puri", "category": "Snack", "serving_size": "1 plate (150g)", "serving_weight_g": 150, "emoji": "🥗", "calories": 180, "protein": 4.0, "carbohydrates": 32.0, "fat": 5.0, "fiber": 3.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Pani Puri (6 pieces)", "regional_name": "Gol Gappa / Puchka", "category": "Snack", "serving_size": "6 pieces", "serving_weight_g": 150, "emoji": "🥣", "calories": 160, "protein": 3.0, "carbohydrates": 28.0, "fat": 5.0, "fiber": 2.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Dhokla (100g)", "regional_name": "Khaman Dhokla", "category": "Snack", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🟡", "calories": 155, "protein": 7.0, "carbohydrates": 28.0, "fat": 2.0, "fiber": 2.5, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Popcorn (salted)", "regional_name": "Salted Popcorn", "category": "Snack", "serving_size": "1 cup (30g)", "serving_weight_g": 30, "emoji": "🍿", "calories": 110, "protein": 3.0, "carbohydrates": 21.0, "fat": 2.0, "fiber": 3.5, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Roasted Chana (100g)", "regional_name": "Bhuna Chana", "category": "Snack", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🌰", "calories": 360, "protein": 20.0, "carbohydrates": 53.0, "fat": 6.0, "fiber": 15.0, "iron_mg": 6.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Makhana (Fox Nuts)", "regional_name": "Roasted Phool Makhana", "category": "Snack", "serving_size": "1 cup (30g)", "serving_weight_g": 30, "emoji": "🌰", "calories": 105, "protein": 3.2, "carbohydrates": 22.0, "fat": 0.2, "fiber": 2.2, "calcium_mg": 50, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 25.0, "vegetarian": True, "vegan": True},

  # Dairy & Health
  {"name": "Full Fat Milk (200ml)", "regional_name": "Doodh", "category": "Dairy", "serving_size": "1 glass (200ml)", "serving_weight_g": 200, "emoji": "🥛", "calories": 130, "protein": 6.4, "carbohydrates": 9.6, "fat": 7.2, "fiber": 0.0, "calcium_mg": 240, "b12_mcg": 0.8, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 15.0, "vegetarian": True, "vegan": False},
  {"name": "Curd / Dahi (100g)", "regional_name": "Fresh Curd", "category": "Dairy", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🥣", "calories": 60, "protein": 3.5, "carbohydrates": 4.0, "fat": 3.2, "fiber": 0.0, "calcium_mg": 150, "b12_mcg": 0.3, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 12.0, "vegetarian": True, "vegan": False},
  {"name": "Greek Yogurt (100g)", "regional_name": "Hung Curd", "category": "Dairy", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🥣", "calories": 100, "protein": 10.0, "carbohydrates": 5.0, "fat": 4.0, "fiber": 0.0, "calcium_mg": 220, "b12_mcg": 0.5, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 40.0, "vegetarian": True, "vegan": False},
  {"name": "Lassi (250ml)", "regional_name": "Sweet Punjabi Lassi", "category": "Dairy", "serving_size": "1 glass (250ml)", "serving_weight_g": 250, "emoji": "🥛", "calories": 150, "protein": 5.5, "carbohydrates": 22.0, "fat": 4.5, "fiber": 0.0, "calcium_mg": 180, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 30.0, "vegetarian": True, "vegan": False},
  {"name": "Buttermilk (Chaas)", "regional_name": "Chaas / Mattha", "category": "Dairy", "serving_size": "1 glass (250ml)", "serving_weight_g": 250, "emoji": "🥛", "calories": 40, "protein": 2.0, "carbohydrates": 5.0, "fat": 1.0, "fiber": 0.0, "calcium_mg": 120, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 12.0, "vegetarian": True, "vegan": False},
  {"name": "Paneer Bhurji", "regional_name": "Spiced Paneer Scramble", "category": "Dairy", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🧀", "calories": 290, "protein": 20.0, "carbohydrates": 6.0, "fat": 20.0, "fiber": 1.5, "calcium_mg": 390, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 60.0, "vegetarian": True, "vegan": False},
  {"name": "Cottage Cheese (100g)", "regional_name": "Paneer Low Fat", "category": "Dairy", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🧀", "calories": 98, "protein": 11.0, "carbohydrates": 3.4, "fat": 4.3, "fiber": 0.0, "calcium_mg": 300, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 45.0, "vegetarian": True, "vegan": False},
  {"name": "Whey Protein Shake", "regional_name": "Protein Shake", "category": "Supplement", "serving_size": "1 scoop (30g)", "serving_weight_g": 30, "emoji": "🥤", "calories": 120, "protein": 25.0, "carbohydrates": 4.0, "fat": 1.5, "fiber": 0.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 80.0, "vegetarian": True, "vegan": False},

  # Rice dishes
  {"name": "Veg Biryani", "regional_name": "Vegetable Dum Biryani", "category": "Rice", "serving_size": "1 plate (300g)", "serving_weight_g": 300, "emoji": "🍚", "calories": 380, "protein": 9.0, "carbohydrates": 60.0, "fat": 12.0, "fiber": 4.5, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 90.0, "vegetarian": True, "vegan": True},
  {"name": "Khichdi", "regional_name": "Moong Dal Khichdi", "category": "Rice", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🍚", "calories": 200, "protein": 8.0, "carbohydrates": 36.0, "fat": 4.0, "fiber": 3.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Pulao", "regional_name": "Matar Vegetable Pulao", "category": "Rice", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🍚", "calories": 250, "protein": 5.0, "carbohydrates": 45.0, "fat": 7.0, "fiber": 3.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 40.0, "vegetarian": True, "vegan": True},
  {"name": "Curd Rice", "regional_name": "Thayir Sadam", "category": "Rice", "serving_size": "1 bowl (220g)", "serving_weight_g": 220, "emoji": "🍚", "calories": 220, "protein": 6.0, "carbohydrates": 38.0, "fat": 5.0, "fiber": 1.5, "calcium_mg": 160, "protein_quality_score": 0.70, "bioavailability_label": "High", "price_estimate": 35.0, "vegetarian": True, "vegan": False},

  # Breakfast specials
  {"name": "Uttapam", "regional_name": "Onion Uttapam", "category": "South Indian", "serving_size": "1 piece (100g)", "serving_weight_g": 100, "emoji": "🥞", "calories": 215, "protein": 6.0, "carbohydrates": 32.0, "fat": 7.0, "fiber": 2.5, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 40.0, "vegetarian": True, "vegan": True},
  {"name": "Medu Vada", "regional_name": "Urad Dal Vada", "category": "South Indian", "serving_size": "1 piece (50g)", "serving_weight_g": 50, "emoji": "🍩", "calories": 195, "protein": 6.0, "carbohydrates": 24.0, "fat": 9.0, "fiber": 2.0, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 15.0, "vegetarian": True, "vegan": True},
  {"name": "Aloo Paratha (stuffed)", "regional_name": "Aloo Paratha", "category": "Bread", "serving_size": "1 piece (100g)", "serving_weight_g": 100, "emoji": "🥞", "calories": 250, "protein": 5.0, "carbohydrates": 36.0, "fat": 10.0, "fiber": 3.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": False},
  {"name": "Besan Chilla", "regional_name": "Gram Flour Chilla", "category": "Breakfast", "serving_size": "1 piece (80g)", "serving_weight_g": 80, "emoji": "🥞", "calories": 180, "protein": 9.0, "carbohydrates": 22.0, "fat": 7.0, "fiber": 4.0, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Vermicelli Upma", "regional_name": "Sevai Upma", "category": "Breakfast", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🍝", "calories": 200, "protein": 5.0, "carbohydrates": 35.0, "fat": 6.0, "fiber": 2.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Banana (1 medium)", "regional_name": "Kela", "category": "Fruit", "serving_size": "1 piece (118g)", "serving_weight_g": 118, "emoji": "🍌", "calories": 89, "protein": 1.1, "carbohydrates": 23.0, "fat": 0.3, "fiber": 2.6, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 6.0, "vegetarian": True, "vegan": True},
  {"name": "Apple", "regional_name": "Seb", "category": "Fruit", "serving_size": "1 piece (150g)", "serving_weight_g": 150, "emoji": "🍎", "calories": 72, "protein": 0.4, "carbohydrates": 19.0, "fat": 0.2, "fiber": 3.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Papaya (100g)", "regional_name": "Papita", "category": "Fruit", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🍈", "calories": 43, "protein": 0.5, "carbohydrates": 11.0, "fat": 0.3, "fiber": 1.8, "vitamin_c_mg": 60.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 15.0, "vegetarian": True, "vegan": True},

  # Sweets & Desserts
  {"name": "Gulab Jamun (1 piece)", "regional_name": "Gulab Jamun", "category": "Sweet", "serving_size": "1 piece (50g)", "serving_weight_g": 50, "emoji": "🍬", "calories": 150, "protein": 2.0, "carbohydrates": 25.0, "fat": 5.0, "fiber": 0.2, "protein_quality_score": 0.50, "bioavailability_label": "Low", "price_estimate": 20.0, "vegetarian": True, "vegan": False},
  {"name": "Rasgulla (1 piece)", "regional_name": "Chhena Rasgulla", "category": "Sweet", "serving_size": "1 piece (50g)", "serving_weight_g": 50, "emoji": "🍬", "calories": 106, "protein": 3.0, "carbohydrates": 20.0, "fat": 2.0, "fiber": 0.0, "protein_quality_score": 0.70, "bioavailability_label": "Medium", "price_estimate": 20.0, "vegetarian": True, "vegan": False},
  {"name": "Kheer (100g)", "regional_name": "Rice Kheer / Payasam", "category": "Sweet", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🍮", "calories": 160, "protein": 4.0, "carbohydrates": 28.0, "fat": 4.0, "fiber": 0.5, "calcium_mg": 120, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 30.0, "vegetarian": True, "vegan": False},
  {"name": "Halwa (100g)", "regional_name": "Suji Halwa", "category": "Sweet", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🍮", "calories": 280, "protein": 3.0, "carbohydrates": 42.0, "fat": 12.0, "fiber": 1.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": False},
  {"name": "Jalebi (100g)", "regional_name": "Crispy Jalebi", "category": "Sweet", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🟠", "calories": 360, "protein": 2.0, "carbohydrates": 74.0, "fat": 7.0, "fiber": 0.2, "protein_quality_score": 0.30, "bioavailability_label": "Low", "price_estimate": 35.0, "vegetarian": True, "vegan": True},

  # Nuts & Seeds
  {"name": "Almonds (28g)", "regional_name": "Badam Giri", "category": "Snack", "serving_size": "28g", "serving_weight_g": 28, "emoji": "🌰", "calories": 164, "protein": 6.0, "carbohydrates": 6.0, "fat": 14.0, "fiber": 3.5, "calcium_mg": 75, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Peanuts (100g)", "regional_name": "Moongphali", "category": "Snack", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🥜", "calories": 567, "protein": 26.0, "carbohydrates": 16.0, "fat": 49.0, "fiber": 8.5, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Cashews (28g)", "regional_name": "Kaju", "category": "Snack", "serving_size": "28g", "serving_weight_g": 28, "emoji": "🌰", "calories": 157, "protein": 5.0, "carbohydrates": 9.0, "fat": 12.0, "fiber": 1.0, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 35.0, "vegetarian": True, "vegan": True},
  {"name": "Peanut Butter (2tbsp)", "regional_name": "Moongphali Butter", "category": "Health Food", "serving_size": "2 tbsp (32g)", "serving_weight_g": 32, "emoji": "🥜", "calories": 190, "protein": 7.0, "carbohydrates": 6.0, "fat": 16.0, "fiber": 2.0, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 20.0, "vegetarian": True, "vegan": True},

  # Beverages
  {"name": "Chai (masala tea)", "regional_name": "Masala Chai", "category": "Beverage", "serving_size": "1 cup (150ml)", "serving_weight_g": 150, "emoji": "☕", "calories": 80, "protein": 2.0, "carbohydrates": 12.0, "fat": 2.5, "fiber": 0.0, "protein_quality_score": 0.80, "bioavailability_label": "High", "price_estimate": 10.0, "vegetarian": True, "vegan": False},
  {"name": "Black Coffee", "regional_name": "Kadi Coffee", "category": "Beverage", "serving_size": "1 cup (150ml)", "serving_weight_g": 150, "emoji": "☕", "calories": 5, "protein": 0.3, "carbohydrates": 1.0, "fat": 0.0, "fiber": 0.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 15.0, "vegetarian": True, "vegan": True},
  {"name": "Fresh Lime Soda", "regional_name": "Nimbu Pani", "category": "Beverage", "serving_size": "1 glass (250ml)", "serving_weight_g": 250, "emoji": "🍋", "calories": 50, "protein": 0.2, "carbohydrates": 13.0, "fat": 0.0, "fiber": 0.2, "vitamin_c_mg": 30.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Coconut Water", "regional_name": "Nariyal Pani", "category": "Beverage", "serving_size": "1 glass (250ml)", "serving_weight_g": 250, "emoji": "🥥", "calories": 46, "protein": 1.7, "carbohydrates": 8.9, "fat": 0.5, "fiber": 1.1, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 50.0, "vegetarian": True, "vegan": True},
  {"name": "Aam Panna (raw mango)", "regional_name": "Kairi Panna", "category": "Beverage", "serving_size": "1 glass (200ml)", "serving_weight_g": 200, "emoji": "🥭", "calories": 80, "protein": 0.5, "carbohydrates": 20.0, "fat": 0.2, "fiber": 1.0, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 30.0, "vegetarian": True, "vegan": True},

  # Non-veg extras
  {"name": "Chicken Breast (100g)", "regional_name": "Lean Chicken", "category": "Non-Veg", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🍗", "calories": 165, "protein": 31.0, "carbohydrates": 0.0, "fat": 3.6, "fiber": 0.0, "b12_mcg": 0.4, "iron_mg": 1.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 60.0, "vegetarian": False},
  {"name": "Keema Matar", "regional_name": "Minced Mutton Peas", "category": "Non-Veg", "serving_size": "1 bowl (200g)", "serving_weight_g": 200, "emoji": "🥩", "calories": 340, "protein": 26.0, "carbohydrates": 14.0, "fat": 22.0, "fiber": 3.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 160.0, "vegetarian": False},
  {"name": "Egg White (1)", "regional_name": "Anda Safedi", "category": "Egg", "serving_size": "1 piece (33g)", "serving_weight_g": 33, "emoji": "🥚", "calories": 17, "protein": 3.6, "carbohydrates": 0.2, "fat": 0.0, "fiber": 0.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 8.0, "vegetarian": False, "contains_egg": True},
  {"name": "Scrambled Eggs (2)", "regional_name": "Egg Scramble", "category": "Egg", "serving_size": "1 serving (120g)", "serving_weight_g": 120, "emoji": "🍳", "calories": 182, "protein": 12.0, "carbohydrates": 1.0, "fat": 14.0, "fiber": 0.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 35.0, "vegetarian": False, "contains_egg": True},
  {"name": "Fish Fry (100g)", "regional_name": "Masala Fried Fish", "category": "Non-Veg", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🐟", "calories": 200, "protein": 22.0, "carbohydrates": 4.0, "fat": 10.0, "fiber": 0.2, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 90.0, "vegetarian": False},
  {"name": "Chicken Kebab (2pc)", "regional_name": "Reshmi / Seekh Kebab", "category": "Non-Veg", "serving_size": "2 pieces (120g)", "serving_weight_g": 120, "emoji": "🍗", "calories": 240, "protein": 32.0, "carbohydrates": 5.0, "fat": 10.0, "fiber": 1.0, "protein_quality_score": 1.0, "bioavailability_label": "High", "price_estimate": 110.0, "vegetarian": False},

  # Health foods & Superfoods
  {"name": "Sprouts Salad", "regional_name": "Sprouted Moong Salad", "category": "Health Food", "serving_size": "1 bowl (150g)", "serving_weight_g": 150, "emoji": "🌱", "calories": 100, "protein": 8.0, "carbohydrates": 16.0, "fat": 1.0, "fiber": 5.5, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Oats (cooked)", "regional_name": "Porridge Oats", "category": "Breakfast", "serving_size": "1 bowl (180g)", "serving_weight_g": 180, "emoji": "🥣", "calories": 166, "protein": 6.0, "carbohydrates": 28.0, "fat": 3.6, "fiber": 4.0, "protein_quality_score": 0.50, "bioavailability_label": "Medium", "price_estimate": 25.0, "vegetarian": True, "vegan": True},
  {"name": "Quinoa (cooked)", "regional_name": "Quinoa Grain", "category": "Health Food", "serving_size": "1 cup (150g)", "serving_weight_g": 150, "emoji": "🥣", "calories": 222, "protein": 8.0, "carbohydrates": 39.0, "fat": 3.6, "fiber": 5.0, "protein_quality_score": 0.70, "bioavailability_label": "High", "price_estimate": 55.0, "vegetarian": True, "vegan": True},
  {"name": "Tofu (100g)", "regional_name": "Soy Bean Curd", "category": "Health Food", "serving_size": "100g", "serving_weight_g": 100, "emoji": "🍱", "calories": 76, "protein": 8.0, "carbohydrates": 2.0, "fat": 4.5, "fiber": 1.5, "calcium_mg": 320, "protein_quality_score": 0.70, "bioavailability_label": "High", "price_estimate": 30.0, "vegetarian": True, "vegan": True},
  {"name": "Green Salad", "regional_name": "Cucumber Tomato Salad", "category": "Health Food", "serving_size": "1 bowl (150g)", "serving_weight_g": 150, "emoji": "🥗", "calories": 50, "protein": 2.0, "carbohydrates": 9.0, "fat": 0.5, "fiber": 3.2, "protein_quality_score": 0.40, "bioavailability_label": "Low", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Protein Ladoo", "regional_name": "Besan Gond Protein Ladoo", "category": "Health Food", "serving_size": "1 piece (40g)", "serving_weight_g": 40, "emoji": "🟤", "calories": 130, "protein": 8.0, "carbohydrates": 14.0, "fat": 5.0, "fiber": 2.0, "protein_quality_score": 0.70, "bioavailability_label": "High", "price_estimate": 35.0, "vegetarian": True, "vegan": False},
  {"name": "Soya Chunks (100g)", "regional_name": "Defatted Soya Flour Chunks", "category": "Health Food", "serving_size": "100g (dry)", "serving_weight_g": 100, "emoji": "🍱", "calories": 345, "protein": 52.0, "carbohydrates": 33.0, "fat": 0.5, "fiber": 13.0, "calcium_mg": 350, "iron_mg": 14.2, "protein_quality_score": 0.70, "bioavailability_label": "High", "price_estimate": 22.0, "vegetarian": True, "vegan": True},
  {"name": "Sattu Drink", "regional_name": "Roasted Gram Drink", "category": "Beverage", "serving_size": "1 glass (300ml)", "serving_weight_g": 300, "emoji": "🥤", "calories": 140, "protein": 9.0, "carbohydrates": 22.0, "fat": 2.0, "fiber": 5.0, "iron_mg": 3.0, "protein_quality_score": 0.60, "bioavailability_label": "Medium", "price_estimate": 20.0, "vegetarian": True, "vegan": True},
  {"name": "Pea Protein (scoop)", "regional_name": "Vegan Pea Protein", "category": "Supplement", "serving_size": "1 scoop (30g)", "serving_weight_g": 30, "emoji": "🥤", "calories": 100, "protein": 20.0, "carbohydrates": 2.0, "fat": 0.5, "fiber": 1.0, "protein_quality_score": 0.70, "bioavailability_label": "High", "price_estimate": 70.0, "vegetarian": True, "vegan": True},
  {"name": "Til (Sesame) Chikki", "regional_name": "Til Patti", "category": "Sweet", "serving_size": "1 piece (30g)", "serving_weight_g": 30, "emoji": "🟡", "calories": 200, "protein": 5.0, "carbohydrates": 24.0, "fat": 10.0, "fiber": 2.5, "calcium_mg": 290, "protein_quality_score": 0.50, "bioavailability_label": "Low", "price_estimate": 15.0, "vegetarian": True, "vegan": True}
]

def seed_foods():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        new_count = 0
        updated_count = 0
        for f_data in INDIAN_FOODS_DATASET:
            existing = db.query(Food).filter(Food.name == f_data["name"]).first()
            if not existing:
                food = Food(**f_data)
                db.add(food)
                new_count += 1
            else:
                for k, v in f_data.items():
                    setattr(existing, k, v)
                updated_count += 1
        db.commit()
        total = db.query(Food).count()
        print(f"✅ Successfully processed {len(INDIAN_FOODS_DATASET)} foods. Total in database: {total} Indian food items.")
    except Exception as e:
        db.rollback()
        print(f"❌ Error seeding foods: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_foods()
